sudo: required
services:
    - docker
before_install:
    - docker build -t rawat2308/react-test -f ./client/Dockerfile.dev ./client
script:    
    - docker run rawat2308/react-test npm test -- --coverage 

after_success:
    - docker build -t rawat2308/multi-client ./client
    - docker build -t rawat2308/multi-nginx ./nginx
    - docker build -t rawat2308/multi-server ./server
    - docker build -t rawat2308/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push rawat2308/multi-client
    - docker push rawat2308/multi-nginx
    - docker push rawat2308/multi-server
    - docker push rawat2308/multi-worker
    